#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

tempdir="$(mktemp -d)"
# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$tempdir"

dpkg --install $tempdir/webmin.deb

ynh_safe_rm "$tempdir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_replace --match="port=10000" --replace="port=$port" --file="/etc/webmin/miniserv.conf"
ynh_replace --match="listen=10000" --replace="listen=$port" --file="/etc/webmin/miniserv.conf"

# Calculate and store the config file checksum into the app settings
ynh_store_file_checksum "/etc/webmin/miniserv.conf"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated systemd config
systemctl daemon-reload
systemctl enable $app.service --quiet

yunohost service add $app --description="Webmin Daemon"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service=$app --action="restart" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
